### ISSUE TITLE
[Help] Tag does not match mandatory sequence component.

### ISSUE THREAD

**Issue by danilocgraciano** [beanit/iec61850bean#14]
Hi,

Could someone help me with the exception below? I followed the examples and tested using IED Explorer.

Using com.beanit.iec61850bean.clientgui.ClientGui everything works.

`16:55:53.204 [iec61850bean-server-thread-1] DEBUG com.beanit.iec61850bean.ServerAssociation - Connection was closed by client.
16:56:03.533 [iec61850bean-server-thread-1] WARN com.beanit.iec61850bean.ServerAssociation - IOException decoding received MMS request PDU.
java.io.IOException: Tag does not match mandatory sequence component.
	at com.beanit.iec61850bean.internal.mms.asn1.ConfirmedRequestPDU.decode(ConfirmedRequestPDU.java:112)
	at com.beanit.iec61850bean.internal.mms.asn1.MMSpdu.decode(MMSpdu.java:209)
	at com.beanit.iec61850bean.ServerAssociation.listenForMmsRequest(ServerAssociation.java:450)
	at com.beanit.iec61850bean.ServerAssociation.handleConnection(ServerAssociation.java:248)
	at com.beanit.iec61850bean.ServerAssociation.handleNewAssociation(ServerAssociation.java:155)
	at com.beanit.iec61850bean.ServerSap.connectionIndication(ServerSap.java:307)
	at com.beanit.iec61850bean.AcseListener.connectionIndication(AcseListener.java:31)
	at com.beanit.josistack.ServerAcseSap.connectionIndication(ServerAcseSap.java:119)
	at com.beanit.jositransport.ServerThread$ConnectionHandler.run(ServerThread.java:144)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)`

Please look at this picture:
[https://github.com/danilocgraciano/iec-server/blob/master/ied_explorer.png](url)

And this is the repo: [https://github.com/danilocgraciano/iec-server](url)

Thanks.

**Comment by pavel-ch** [comment]
There are several issues identified using IedExplorer with iec61850bean server, all are linked to the missing implementations in iec61850bean library:
1) missing implementation of "identify" combined with a wrong announcement of implementing it (see #22 ). This generates a stack trace but does not prevent communication.
2) Read request: iec61850bean does not implement Read request with SpecificationWithResult = True; in that case the association is closed
![image](https://user-images.githubusercontent.com/771816/116226632-8460e980-a753-11eb-9c24-a5f77c63da23.png)

3) read request: iec61850bean does not support reading at FC level like this:
![image](https://user-images.githubusercontent.com/771816/116226548-62676700-a753-11eb-8c11-74f3fa746556.png)


although it is completely legal in 61850.

In IedExplorer, reading values at start can be switched OFF:
![image](https://user-images.githubusercontent.com/771816/116226136-ec630000-a752-11eb-91d7-7bdd4c9e2b81.png)

But the 2) point prevents using the IedExplorer in the current version.

**Comment by pavel-ch** [comment]
There is a new IedExplorer release to allow the above reading / Service release 0.79m 2021/04/27
You have to switch OFF Read Values and With Spec.
You must read values of interest by hand from the context menu.
![image](https://user-images.githubusercontent.com/771816/116238125-48348580-a761-11eb-90e1-5321cc5a64cf.png)
