### ISSUE TITLE
i got error IED Connection Lost . when i used 3rd party IED Scout . 

### ISSUE THREAD

**Issue by dhirajthaokar** [beanit/iec61850bean#39]
![photo_2023-10-10_17-37-31](https://github.com/beanit/iec61850bean/assets/17737681/a0988435-77d7-4993-b90d-a5d0b8e7b27b)

when i enable reports then i got error which is mention in image .  

exception is :  java.io.EOFException
	at java.base/java.io.DataInputStream.readByte(DataInputStream.java:272)
	at com.beanit.jositransport.TConnection.receive(TConnection.java:501)
	at com.beanit.josistack.AcseAssociation.receive(AcseAssociation.java:838)
	at com.seiritech.alectra.beanit.iec61850bean.ServerAssociation.listenForMmsRequest(ServerAssociation.java:428)
	at com.seiritech.alectra.beanit.iec61850bean.ServerAssociation.handleConnection(ServerAssociation.java:248)
	at com.seiritech.alectra.beanit.iec61850bean.ServerAssociation.handleNewAssociation(ServerAssociation.java:155)
	at com.seiritech.alectra.beanit.iec61850bean.ServerSap.connectionIndication(ServerSap.java:307)
	at com.seiritech.alectra.beanit.iec61850bean.AcseListener.connectionIndication(AcseListener.java:31)
	at com.beanit.josistack.ServerAcseSap.connectionIndication(ServerAcseSap.java:119)
	at com.beanit.jositransport.ServerThread$ConnectionHandler.run(ServerThread.java:144)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
13:01:49.360 [iec61850bean-server-thread-1] DEBUG c.s.a.b.i.ServerAssociation - Connection was closed by client.

**Comment by dhirajthaokar** [comment]
icd file report block is   
   <DataSet name="dataset1" desc="">
                            <FCDA ldInst="lDevice1" lnClass="MMXU" fc="MX" lnInst="1" doName="TotW" />
                            <FCDA ldInst="lDevice1" lnClass="MMXU" fc="MX" lnInst="1" doName="W.phsA" daName="cVal.mag.f" />
                        </DataSet>
                        <ReportControl name="urcb1" confRev="0" datSet="dataset1" buffered="false" rptID="urcb1" intgPd="5000" bufTime="0">
                            <TrgOps dchg="true" qchg="true" dupd="true" period="true" gi="true" />
                            <OptFields dataSet="true" bufOvfl="true" configRef="true" dataRef="true" entryID="false" reasonCode="true" timeStamp="true" seqNum="true"/>
                            <RptEnabled max="3"/>
                        </ReportControl>

**Comment by tusky2015** [comment]
BdaReasonForInclusion.java
modify (line 19) maxNumBits from 7  to 6

**Comment by dhirajthaokar** [comment]
thanks for reply .  i gone with this solution . but still i got above error . when i  refer 1 st image then connection will loss and when i refer 2nd image then connection is success.   
![1 IMAGE](https://github.com/beanit/iec61850bean/assets/17737681/b9365d60-f55f-44ef-98d7-a8ccc8ffdc4c)
![2ND IMAGE](https://github.com/beanit/iec61850bean/assets/17737681/aecafb66-4973-4401-ba8b-b45cd1f75b1c)..

**Comment by dhirajthaokar** [comment]
after success connection, it  does not work with Siemens RTU. its shows NT(no transmit).   i use Rpi as  61850 server 
and RTU is client .  icd file is attached.

  
[server_icd.txt](https://github.com/beanit/iec61850bean/files/13407450/server_icd.txt)

**Comment by dgefremov** [comment]
According to source code transmitting ConfRevision, DataReferences, BufferOverflow, EntryId in RCB is not supported.
When client tries to set these parameters to RCB the "access violation" error should be sent. 
Replace this code block in _src/main/java/com/beanit/iec61850bean/ServerAssociation.java_ (line number 1399)


```
if (!((BdaOptFlds) modelNode).isBufferOverflow()
                && !((BdaOptFlds) modelNode).isConfigRevision()
                && !((BdaOptFlds) modelNode).isDataReference()
                && !((BdaOptFlds) modelNode).isEntryId()) {
              ((BasicDataAttribute) modelNode).setValueFrom((BasicDataAttribute) fcModelNodeCopy);
              return writeSuccess;
```


with the following code:
```
if (!((BdaOptFlds) fcModelNodeCopy).isBufferOverflow()
                && !((BdaOptFlds) fcModelNodeCopy).isConfigRevision()
                && !((BdaOptFlds) fcModelNodeCopy).isDataReference()
                && !((BdaOptFlds) fcModelNodeCopy).isEntryId()) {
              ((BasicDataAttribute) modelNode)
                  .setValueFrom((BasicDataAttribute) fcModelNodeCopy);
              return writeSuccess;
```
